import javax.swing.*;
import java.awt.*;

public class SayHelloToSwing {
    public static void main(String[] args) {
        JFrame frame = new JFrame("Hello");

        JPanel panel = new JPanel();
        panel.setPreferredSize(new Dimension(300, 200));
        panel.add(new JTextField("Enter username"));

        JPanel addEmployeeInfo = new JPanel();
        addEmployeeInfo.add(new JList<String>());


        JLabel label = new JLabel("Don't Worry");
        label.setHorizontalAlignment(SwingConstants.CENTER);

        JButton hellobutton = new JButton("Click Me");

        JTextField helloBox = new JTextField();

        JTabbedPane tabbedPane = new JTabbedPane(1);
        tabbedPane.addTab("Add User", panel);
        tabbedPane.addTab("Add Employee", addEmployeeInfo);

//        JMenu mainMenu = new JMenu("Main");
//        mainMenu.add(new JMenuItem("Add a New User"));
//        mainMenu.add(new JMenuItem("Show List"));


        //frame.add(panel, BorderLayout.CENTER);
        frame.add(label, BorderLayout.SOUTH);
        frame.add(hellobutton, BorderLayout.WEST);
        frame.add(tabbedPane, BorderLayout.CENTER);


        frame.pack();
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
        frame.setVisible(true);
    }


    {
// GUI initializer generated by IntelliJ IDEA GUI Designer
// >>> IMPORTANT!! <<<
// DO NOT EDIT OR ADD ANY CODE HERE!
        $$$setupUI$$$();
    }

    /**
     * Method generated by IntelliJ IDEA GUI Designer
     * >>> IMPORTANT!! <<<
     * DO NOT edit this method OR call it in your code!
     *
     * @noinspection ALL
     */
    private void $$$setupUI$$$() {
        final JPanel panel1 = new JPanel();
        panel1.setLayout(new com.intellij.uiDesigner.core.GridLayoutManager(1, 1, new Insets(0, 0, 0, 0), -1, -1));
    }
}
